server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BloodCenter
    username: isa
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect