server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BloodCenter
    username: isa
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      data-locations: classpath:import.sql
  mail:
    host: smtp.gmail.com
    port: 587
    username: isaproject57@gmail.com
    password: bbnrjlooxrmkcgwi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    jwt:
      secret: "opaopa"